import NavBar from "@/components/navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { twMerge } from "tailwind-merge";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={twMerge(inter.className, "dark:bg-black dark:text-white")}
      >
        <header className="fixed left-0 right-0 bottom-0 sm:top-0 h-20 bg-white/80 dark:bg-black/80 backdrop-blur-xl z-10">
          <NavBar className="max-w-lg m-auto" />
        </header>
        {children}
      </body>
    </html>
  );
}
